# Changes here will be overwritten by Copier
_commit: 2024.10.10
_src_path: gh:zenml-io/template-e2e-batch
data_quality_checks: true
email: ''
full_name: Kevin Hickey
hyperparameters_tuning: true
metric_compare_promotion: true
notify_on_failures: true
notify_on_successes: true
open_source_license: mit
product_name: trash_can_2_0
project_name: pitch_predict
target_environment: staging
version: 0.0.1
zenml_server_url: ''
