# MIT License
# 
# Copyright (c) Kevin Hickey 2024
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 

# environment configuration
settings:
  docker:
    required_integrations:
      - aws
      - evidently
      - kubeflow
      - kubernetes
      - mlflow
      - sklearn
      - slack

# configuration of steps  
steps:
  model_trainer:
    parameters:
      name: trash_can_2_0
  promote_with_metric_compare:
    parameters:
      mlflow_model_name: trash_can_2_0
  notify_on_success:
    parameters:
      notify_on_success: False

# configuration of the Model Control Plane
model:
  name: trash_can_2_0
  license: mit
  description: trash_can_2_0 E2E Batch Use Case
  audience: All ZenML users
  use_cases: |
    The pitch_predict project demonstrates how the most important steps of 
    the ML Production Lifecycle can be implemented in a reusable way remaining 
    agnostic to the underlying infrastructure, and shows how to integrate them together 
    into pipelines for Training and Batch Inference purposes.
  ethics: No impact.
  tags:
  - e2e
  - batch
  - sklearn
  - from template
  - ZenML delivered

# pipeline level extra configurations
extra:
  notify_on_failure: True
# pipeline level parameters
parameters:
  target_env: staging
  # This set contains all the model configurations that you want 
  # to evaluate during hyperparameter tuning stage.
  model_search_space:
    random_forest:
      model_package: sklearn.ensemble
      model_class: RandomForestClassifier
      search_grid:
        criterion:
          - gini
          - entropy
        max_depth:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
        min_samples_leaf:
          range:
            start: 1
            end: 10
        n_estimators:
          range:
            start: 50
            end: 500
            step: 25
    decision_tree:
      model_package: sklearn.tree
      model_class: DecisionTreeClassifier
      search_grid:
        criterion:
          - gini
          - entropy
        max_depth:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
        min_samples_leaf:
          range:
            start: 1
            end: 10